version: '3.8'

services:
  supabase:
    image: supabase/postgres:latest
    container_name: supabase_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MTQ4ODUyNDJnb2lkYXpvdnNraWJpZGk=
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: my_spring_api
    ports:
      - "8080:8080"
    depends_on:
      - supabase
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.hokbofyvzdugplrhoghf&password=MTQ4ODUyNDJnb2lkYXpvdnNraWJpZGk=
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: MTQ4ODUyNDJnb2lkYXpvdnNraWJpZGk=
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  supabase_data: