spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: 3600000
    user:
      name: admin
      password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:file:.env[.yaml]

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: "/swagger-ui.html"
  show-actuator: true