spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: Cryptic
    password: velkom3161127
    url: jdbc:postgresql://localhost:5432/library_db
  security:
    user:
      name: admin
      password: admin

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: "/swagger-ui.html"
  show-actuator: true