spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: MTQ4ODUyNDJnb2lkYXpvdnNraWJpZGk=
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.hokbofyvzdugplrhoghf&password=MTQ4ODUyNDJnb2lkYXpvdnNraWJpZGk=
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  security:
    jwt:
      secret-key: IqYBdEd70/GLhXYO0JDdiBhTnAk/zxS+gWxtVqTv7oLDmmU+Ze2V6lrkAuVDyLsWesxmRZD9MMDhb25cQWkc/w==
      expiration-time: 3600000
    user:
      name: admin
      password: admin
  mail:
    host: smtp.gmail.com
    port: 465
    username: luckyartem901@gmail.com
    password: iovy wmcf myza yzro
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: "/swagger-ui.html"
  show-actuator: true

logging:
  level:
    org:
      springframework:
        security: DEBUG